version: '3.8'

services:
  api:
    build: .
    container_name: bookstore-api
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - bookstore-network

networks:
  bookstore-network:
    driver: bridge